language: node_js
node_js:
  - '8'
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
addons:
  chrome: stable
before_script:
  - npm run lint;
  - npm run build;
  - npm run compile-umd;
  - npm run build-gallery;
  - npm run build-test;
