language: node_js
node_js:
  - '8'
dist: trusty
sudo: true
addons:
  chrome: stable
before_script:
  - npm run lint;
  - npm run build;
  - npm run compile-umd;
  - npm run build-gallery;
  - npm run build-test;
