language: node_js
node_js:
  - '8'
dist: trusty
sudo: false
addons:
  chrome: stable
cache:
  directories:
    - "node_modules"
before_script:
  - npm run lint;
  - npm run build;
  - npm run compile-umd;
  - npm run minimize;
  - npm run build-test;
