language: node_js
node_js:
  - '8'
addons:
  firefox: latest
sudo: false
cache:
  directories:
    - "node_modules"
before_script:
  - npm run build-all;
  - export DISPLAY=:99.0;
  - sh -e /etc/init.d/xvfb start;
  - set -e;
