language: node_js
node_js:
  - '5'
addons:
  firefox: latest
sudo: false
install:
  - npm install
  - npm install -g bower
  - npm install -g gulp
  - bower install
script:
  - export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    set -e;
    npm run clean;
    npm run build;
    npm run test;
    npm run test-legacy;
